name: Build & Draft release

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required to fetch tags

      - name: Get latest tag
        id: get_tag
        shell: bash
        run: |
          git fetch --tags
          TAG=$(git describe --tags --abbrev=0)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: swatinem/rust-cache@v2

      - name: Install frontend dependencies
        run: npm install

      - name: Build and create draft release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ steps.get_tag.outputs.tag }}
          releaseName: 'App ${{ steps.get_tag.outputs.tag }}'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false